### PR TITLE
fix: fixed #256 static create instance should check all default attri…

### LINKED ISSUE #256: [bug] static create instance should check all default attributes settings
```js
class User {
  name: { type: STRING, allowNull: false },
...
}

const u = await User.create({ email: 'ssss' });
/**
current throwing database error:

code: "ER_NO_DEFAULT_FOR_FIELD"
errno: 1364
sqlState: "HY000"
sqlMessage: "Field 'name' doesn't have a default value"

It should be:
throw new LeoricValidateError('notNull', 'name')
**/

```

### PR DESCRIPTION
**Pull request by JimmyDaddy**
…butes settings

### CODE REVIEW

File: src/adapters/sequelize.js [hunk 1]
```diff
@@ -238,9 +238,6 @@ module.exports = Bone => {
     }
 
     static build(values, options = {}) {
```
Comment (JimmyDaddy) [inline src/adapters/sequelize.js:240]: sequelize Model.build doesn't validate attributes, only validate values before persisting data

File: src/bone.js [hunk 2]
```diff
@@ -736,7 +724,12 @@ class Bone {
     }
 
     if (opts.validate !== false) {
-      this._validateAttributes();
+      const validateValues = {};
+      for (const key in attributes) {
+        if (attributes[key].primaryKey) continue;
+        validateValues[key] = this[key];
+      }
+      this._validateAttributes(validateValues);
```
Comment (JimmyDaddy) [inline src/bone.js:732]: It should validate all set values before create an instance

**Review by cyjake — APPROVED** [review]
