### PR TITLE
fix: raw query relpacements fix #149

### LINKED ISSUE #149: query(sql, { replacements })
currently leoric supports  `driver.query('UPDATE users SET name = ?', [ 'Leah' ])`, better support following way as well:

```js
driver.query('UPDATE users SET name = :name', {
  replacements: {
    name: 'Leah',
  }
});
```

or simplify it with: 

```js
driver.query('UPDATE users SET name = :name', {
  name: 'Leah',
});
```

### PR DESCRIPTION
**Pull request by JimmyDaddy**
attr

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -169,12 +169,53 @@ class Realm {
...
-    const { rows, fields, ...others } = await this.driver.query(query, values, opts);
+    let res, fieldRes, restRes = {};
+    if (values && typeof values === 'object' && !Array.isArray(values)) {
+      query = query + ' ';
+      let valueResults = [];
+      const replaceTemplates = query.match(/\s:\w+\s/g);
+      const templateKeys = replaceTemplates.map((t) => t.trim().split(':')[1]);
+      let replacementKeys;
+      let replacements = {};
+      if ('replacements' in values) {
```
Comment (JimmyDaddy) [inline index.js:180]:
```js
driver.query('UPDATE users SET name = :name', {
  replacements: {
    name: 'Leah',
  }
});
```

File: index.js [hunk 2]
```diff
@@ -169,12 +169,53 @@ class Realm {
...
+        const { model, connection } = values;
+        replacements = values.replacements;
+        if (replacements == null) {
+          throw new Error('[leoric] replacements not match with values in raw query');
+        }
+        if (model) opts.model = model;
+        if (connection) opts.connection = connection;
+      } else {
+        replacements = values;
```
Comment (JimmyDaddy) [inline index.js:189]:
```js
driver.query('UPDATE users SET name = :name', {
  name: 'Leah',
});
```
